### ISSUE TITLE
User 관련 API 작업 TODO

### ISSUE THREAD

**Issue by SL313** [SobunSobun/SobunSobun-BackEnd#3]
### ISSUE 종류

- [x] New Feature
- [ ] Bug Fix
- [ ] Communicate
- [ ] Etc

### ISSUE TASKS

- [x] 회원가입
- [x] 로그인 (non - security)
- [x] 닉네임 중복 확인
- [x] 로그인 재정비 (spring security)
