### ISSUE TITLE
Post 관련 API 작업 TODO

### ISSUE THREAD

**Issue by SL313** [SobunSobun/SobunSobun-BackEnd#4]
### ISSUE 종류

- [x] New Feature
- [ ] Bug Fix
- [ ] Communicate
- [ ] Etc

#### 3주차 작업 (완료)
- [x] 게시글 생성 API
- [x] 게시글 수정 API
- [x] 게시글 삭제 API

#### 4주차 작업 (진행 중)
- [ ] 전체 게시글 조회 API
- [x] 상세 게시글 조회 API
- [ ] 내 게시글 조회 API

**Comment by SL313** [comment]
- 게시물 수정 시, 참여한 사람이 한명이라도 있으면 (if applyNumber > 1) 수정 불가
- 게시물 수정 혹은 삭제 시, 작성자가 아니면 수정 혹은 삭제 불가
- 전체 게시물 조회 및 상세 게시물 조회 아직 X

**Comment by SL313** [comment]
3주차에 이어 4주차에도 Post 관련 작업 내용이 많아 ISSUE reopen 했습니다!

**Comment by SL313** [comment]
페이징 처리 관련 API ISSUE 따로 열겠습니다
