### ISSUE TITLE
User 및 Post 관련 추가 API 작업 TODO

### ISSUE THREAD

**Issue by SL313** [SobunSobun/SobunSobun-BackEnd#9]
### ISSUE 종류

- [x] New Feature
- [ ] Bug Fix
- [ ] Communicate
- [ ] Etc

#### USER
- [x] 회원가입 API 위도 정보 추가
- [x] 회원가입 API 경도 정보 추가
- [x] 이메일 중복 확인 API 추가

#### POST
- [ ] 게시글 생성 API 이미지 정보 추가
- [ ] 게시글 수정 API 이미지 정보 추가

**Comment by SL313** [comment]
게시글 이미지 없음
